### ISSUE TITLE
Contact us page not responsive. 

### ISSUE THREAD

**Issue by vik-y** [zense/spandan#19]
![screenshot_2016-01-25-10-26-54](https://cloud.githubusercontent.com/assets/6398563/12542837/5da1565c-c34e-11e5-86c9-4c01d1cff98c.png)

**Comment by arkokoley** [comment]
The frame for the map is smaller than the required size even on desktops.

**Comment by vik-y** [comment]
Do you know how to fix this?


________________________________

**Comment by vik-y** [comment]
Fixed in Pull Request #21
